source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

inhibit_all_warnings!

abstract_target 'Minnie' do

  pod 'YTKNetwork'
  pod 'SDWebImage'
  pod 'SDWebImage/GIF'
  pod 'Masonry'
  pod 'TZImagePickerController'
  pod 'AVOSCloudIM'
  pod 'MBProgressHUD'
  pod 'MJRefresh', '3.1.15.3'
  pod 'YYText'
  pod 'VIMediaCache'
  pod 'MLeaksFinder'
  pod 'Bugly'
  pod 'YYCategories'
  pod 'Qiniu'
  pod 'WMPageController', '~> 2.4.0'
  #pod 'Fabric'
  #pod 'Crashlytics'
  #pod 'PinYin4Objc'
  #pod 'StreamingKit'
  pod 'Mantle'
  pod 'Aspects', '~> 1.4.1'
  #云信
  pod 'NIMSDK_LITE'
target 'MinnieStudent'
target 'MinnieTeacher'
target 'MinnieManager'

end
